site_name: Feeling the Past Reflection
theme: 
  name: readthedocs
nav:
  - Home: index.md
  - Introduction: introduction.md
  - Source Selection of Historians: source-selection.md
  - Collaboration: collaboration.md
  - Lives in Transit: lives-in-transit.md
  - Marugoto: marugoto.md
  - Digital Databases: goal-of-ftp.md
  - Avoiding Normativity: normativity.md
  - Unmet Goals and Decisions: goals-decisions.md
  - Marugoto as Teaching Tool: teaching-tool.md
  - Conclusion: conclusion.md
  - Bibliography: bibliography.md