site_name: Feeling the Past Reflection
theme: 
  name: readthedocs
nav:
  - Home: index.md
  - Introduction: introduction.md
  - Selected Challenges and Essential Insights:
    - Collaboration using Git: collaboration.md
    - Working with Lives in Transit: lives-in-transit.md
    - Marugoto as a Writing Tool: marugoto.md
    - Digital Databases and Feeling the Past: goal-of-ftp.md
    - Avoiding Normativity: normativity.md
    - Unmet Goals and Practical Decisions: goals-decisions.md
    - Marugoto as Teaching Tool: teaching-tool.md
  - Conclusion: conclusion.md
  - Bibliography: bibliography.md
